name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: |
          cargo build --release
          echo "::set-output name=version::$(target/release/pic2lcd --version)"
      - name: Build Release Mac
        if: matrix.os == 'macos-latest'
        run: |
          strip target/release/pic2lcd
          mkdir -p release
          tar -C ./target/release/ -czvf ./release/pic2lcd-mac.tar.gz ./pic2lcd
      - name: Build Release Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo deb
          strip target/release/pic2lcd
          mkdir -p release
          mv target/debian/*.deb ./release/pic2lcd-linux.deb
          cargo install cargo-aur
          cargo aur
          mv *.tar.gz ./release/pic2lcd-arch-linux.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: false
          files: |
            ./release/pic2lcd-mac.tar.gz
            ./release/pic2lcd-arch-linux.tar.gz
            ./release/pic2lcd-linux.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
